baseURL = 'http://blog.nekolas.com'
languageCode = 'en-us'
title = 'Nekolas'
theme = "gruvbox"
paginate = 6
disqusShortname = "nekolas-blog"

[params]
author = { name = "Nic" }
buildDrafts = true
buildFuture = true
enableGitalk = true
description = "å–œæ¬¢ç¡è§‰"
keywords = [
  "web dev",
  "javascript",
  "reader",
  "blog",
  "programmer",
  "peace & love",
]

titlePrefix = "ğŸ¥¯"
titleSuffix = " "
dateFormat = "2006-01-02"
menuItemPrefix = ""
postTruncateLength = 280
hideGopher = false
disqusAutoLoad = false
disqusAutoLoadCount = true
hasCJKLanguage = true

[params.gitalk] 
    clientID = "3480b37ba3106401db3b" # æ‚¨åˆšæ‰åˆ›å»ºGithub Application çš„ Client ID
    clientSecret = "21c4ceebbeed32c15e79f3f3a2bb59137ce2a242" # æ‚¨åˆšæ‰åˆ›å»ºGithub Application çš„ Client Secret
    repo = "https://github.com/nicopcat" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
    owner = "nicopcat" # æ‚¨çš„GitHub ID
    admin= "nicopcat" # æ‚¨çš„GitHub ID
    id= "location.pathname" # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.

[menu]
[[menu.links]]
name = "posts"
identifier = "å†™ç‚¹ä»€ä¹ˆ"
url = "/posts"
weight = 9999

# [[menu.links]]
# name = "bb"
# identifier = "è¯´ç‚¹ä»€ä¹ˆ"
# url = "/bb"
# weight = 499

[[menu.sections]]
name = "tags"
identifier = "è´´äº›æ ‡ç­¾"
url = "/tags"
weight = 5000

[[menu.sections]]
name = "gallery"
identifier = "èµ°èµ°åœåœ"
url = "/gallery"
weight = 999

[[menu.social]]
name = "Twitter"
url = "https://twitter.com/niqks07"
weight = 1
[[menu.social]]
name = "GitHub"
url = "https://github.com/nicopcat"
weight = 10
[[menu.social]]
name = "Instagram"
url = "https://instagram.com/niqks07"
weight = 30
[[menu.social]]
name = "Email"
url = "mailto:tianfang07@outlook.com"
weight = 100

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xhtml = true
      
[taxonomies]
tag = "tags"
